name: lyra_new
description: "Lyra Safety App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6
  speech_to_text: ^7.1.0

  flutter_map_tile_caching: 10.1.1

  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_database: ^12.1.0
  firebase_app_check: ^0.4.1+2
  firebase_messaging: ^16.0.4


  # Permissions
  permission_handler: ^12.0.0

  # ML
  tflite_flutter: ^0.12.1

  # Maps & Location
  google_maps_flutter: ^2.8.0
  geolocator: ^14.0.2
  latlong2: ^0.9.1
  flutter_map: ^8.2.2
  flutter_polyline_points: ^2.0.0
  http: ^1.2.1
  flutter_foreground_task: ^6.1.2


  # Local storage
  shared_preferences: ^2.5.3

  # Audio
  audioplayers: ^6.0.0
  sensors_plus: ^3.0.2
  noise_meter: ^5.1.0
  device_info_plus: ^12.2.0
  firebase_storage: ^13.0.4
  vibration: ^3.1.4
  telephony: 0.2.0
  path_provider: ^2.1.2
  record: ^6.1.2
  flutter_sound: ^9.2.13
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_foreground: "assets/logo.png"
  adaptive_icon_background: "#ffffff"

flutter_native_splash:
  color: "#E9D7FF"
  image: "assets/logo.png"
  android: true
  ios: true

  android_12:
    image: "assets/logo.png"
    icon_background_color: "#E9D7FF"


fonts:
  - family: Nunito
    fonts:
      - asset: assets/fonts/Nunito-Regular.ttf
      - asset: assets/fonts/Nunito-SemiBold.ttf
      - asset: assets/fonts/Nunito-Bold.ttf


flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/audio/sos_alert.mp3
    - assets/models/ann_risk_model.tflite
    - assets/models/nlp_distress_model.tflite
    - assets/tokenizer/tokenizer.json

